%
% This function preprocesses the input data declared in the supplied input
% file
%
% Input(s):
%   - inpFileName: String, name of the selected input function
%
% Output(s):
%   - simData: Struct, simulation data
%

function [simData] = sim_prepro(inpFileName)

simData = struct(); % Initialize output

eval(inpFileName); % Load input data into this function's workspace

%% Constants

simData.cts = struct(); % Preallocate

if strcmpi(celBod, 'Earth')

    simData.cts.rCelBod = rCelBod; % Celestial body radius [m]
    simData.cts.muCelBod = muCelBod; % Celestial body gravitational parameter [m3s-2]
    simData.cts.ellipsoidModelCelBod = ellipsoidModelCelBod; % Celestial body ellipsoid model
    simData.cts.omgCelBod = omgCelBod; % Celestial body angular velocity [rads-1]
    simData.cts.g0CelBod = g0CelBod; % Celestial body surface gravitational acceleration [ms-2]

    if strcmpi(timeRef, 'J2000')

        % Reference time
        % Instant at which there was no rotation between the ECI and ECEF
        % reference frames

        simData.cts.refTime = ... 
            posixtime(datetime( ... 
            2000, ... 
            1, ... 
            1, ... 
            11, ... 
            58, ... 
            55, ... 
            816, ... 
            'TimeZone', 'UTC'));

    else

        error('The requested time reference: %s is not available', ... 
            timeRef);
        
    end

else

    error('The requested celestial body data: %s is not available', ... 
        celBod);

end

%% Initial conditions

simData.ic = struct(); % Preallocate initial conditions

% Time

simData.ic.initTimeUTC = ... 
    datetime( ... 
    initYear, ... 
    initMonth, ... 
    initDay, ... 
    initHour, ... 
    initMin, ... 
    initSec, ...  
    'TimeZone', 'UTC'); % Initial timestamp (UTC), Matlab datetime format

simData.ic.initTimeUTCPosix = ... 
    posixtime( ... 
    simData.ic.initTimeUTC); % Initial timestamp (UTC), Posix time format

simData.ic.initTimeJulian = ... 
    juliandate(datetime( ... 
    simData.ic.initTimeUTC)); % Initial time (UTC), Julian date format

% Translational state - ECI2ECEF DCM

initCelBodRot = ... 
    (simData.ic.initTimeUTCPosix - ... 
    simData.cts.refTime) * ... 
    simData.cts.omgCelBod; % Initial rotation around Z of the ECEF frame w.r.t ECI [rad]

initCelBodRot = rem(initCelBodRot, 2 * pi); % Wrap to [0, 2pi]

simData.ic.initEci2EcefDCM = [ ... 
    cos(initCelBodRot),      sin(initCelBodRot), 0; ... 
    -1 * sin(initCelBodRot), cos(initCelBodRot), 0; ... 
    0,                       0,                  1]; % Initial ECI 2 ECEF rotation DCM

% Translational state - Inertial

if strcmpi(initCondsTypeTranslational, 'OrbitalParametersCircular')

    if initInc == 0

        [simData.ic.r0, ... % Initial inertial position [m]
            simData.ic.v0 ... % Initial inertial velocity [ms-1]
            ] = keplerian2ijk( ... 
            (initAlt * 1e3) + simData.cts.rCelBod, ... 
            0, ... 
            initInc, ... 
            initRAAN, ... 
            initArgPer, ... 
            initTrueAnomaly, ... 
            trueLon = 0); % Initial position and velocity in inertial frame

    else

        [simData.ic.r0, ... % Initial inertial position [m]
            simData.ic.v0 ... % Initial inertial velocity [ms-1]
            ] = keplerian2ijk( ... 
            (initAlt * 1e3) + simData.cts.rCelBod, ... 
            0, ... 
            initInc, ... 
            initRAAN, ... 
            initArgPer, ... 
            initTrueAnomaly, ... 
            arglat = 0); % Initial position and velocity in inertial frame

    end

    % Translational state - Celestial body centered

    % [simData.ic.r0Ecef, ... % Initial celestial body centered position [m]
    %     simData.ic.v0Ecef, ... % Initial celestial body centered velocity [m]
    %     ~] = ... 
    %     eci2ecef( ... 
    %     simData.ic.initTimeUTC, ... 
    %     simData.ic.r0, ... 
    %     simData.ic.v0); % Initial celestial body centered translational state

    simData.ic.r0Ecef = ... 
        simData.ic.initEci2EcefDCM * ... 
        simData.ic.r0;

    simData.ic.v0Ecef = ... 
        (simData.ic.initEci2EcefDCM * ... 
        simData.ic.v0) - ... 
        cross( ... 
        [0; 0; simData.cts.omgCelBod], ... 
        simData.ic.r0Ecef);
    
    % Translational state - Spherical coordinates
    
    simData.ic.lla0 = ... 
        ecef2lla( ... 
        simData.ic.r0Ecef', ... 
        simData.cts.ellipsoidModelCelBod); % Initial latitude, longitude and altitude [º, º, m]
    
    simData.ic.lla0 = ... 
        [simData.ic.lla0(1) * (pi / 180); ... 
        simData.ic.lla0(2) * (pi / 180); ... 
        simData.ic.lla0(3)]; % Convert lat and lon to radians and stack in column vector

elseif strcmpi(initCondsTypeTranslational, 'LLAIncCirc')

    % Translational state - Spherical coordinates

    simData.ic.lla0 = ... 
        [initLat * (pi / 180); ... 
        initLon * (pi / 180); ... 
        initAlt * 1e-3]; % Convert lat and lon to radians and stack in column vector

    % Translational state - Celestial body centered

    simData.ic.r0Ecef = ... 
        lla2ecef( ... 
        [simData.ic.lla0(1) * (180 / pi), ... 
        simData.ic.lla0(2) * (180 / pi), ... 
        simData.ic.lla0(3)], ... 
        simData.cts.ellipsoidModelCelBod);

else

    error('The requested translational initial conditions type: %s is not available', ... 
        initCondsTypeTranslational);

end

% Rotational state - Attitude

if strcmpi(initCondsTypeRotational, 'EulerAngles')

    simData.ic.att0 = ... 
        eul2quat( ... 
        [initYaw * (pi / 180), ... 
        initPitch * (pi / 180), ... 
        initRoll * (pi / 180)], ... 
        "ZYX"); % Initial inertial to body quaternion [-]

    simData.ic.att0 = ... 
        convertQuatConv(simData.ic.att0', 4);
    
else

    error('The requested rotational initial conditions type: %s is not available', ... 
        initCondsTypeRotational);

end

% Rotational state - Angular velocity

simData.ic.omg0 = [ ... 
    initOmgX * (pi / 180); ... 
    initOmgY * (pi / 180); ... 
    initOmgZ * (pi / 180)]; % Initial angular velocity in body w.r.t inertial [rads-1]

% Fuel mass

simData.ic.initFuelMass = initFuelMass; % Initial fuel mass [kg]

%% Mass properties

simData.massProperties = struct(); % Preallocate

% Store values

simData.massProperties.dryMass = ... 
    dryMass; % Dry mass of the vehicle [kg]

simData.massProperties.fullMass = ... 
    simData.massProperties.dryMass + initFuelMass; % Full vehicle mass [kg]

simData.massProperties.dryInertia = ... 
    dryInertia; % Inertia tensor of the vehicle without fuel [kgm2]

simData.massProperties.fullInertia = ... 
    fullInertia; % Inertia tensor of the vehicle with fuel [kgm2]

% Prepare inertia tensor interpolation

simData.massProperties.inertiaBP = ... 
    [0, simData.massProperties.fullMass]; % Breakpoints for the matrix interpolation

simData.massProperties.inertiaTab = ... 
    zeros( ... 
    size(simData.massProperties.dryInertia, 1), ... 
    size(simData.massProperties.dryInertia, 2), ... 
    length(simData.massProperties.inertiaBP)); % Preallocate

simData.massProperties.inertiaTab(:, :, 1) = ... 
    simData.massProperties.dryInertia; % First matrix page

simData.massProperties.inertiaTab(:, :, 2) = ... 
    simData.massProperties.fullInertia; % Second matrix page

%% Aerodynamic properties

simData.aero.refSurf = ... 
    refSurf; % Reference aerodynamic surface [m2]

simData.aero.dragCoeff = ... 
    dragCoeff; % Drag coefficient (assumed constant) [-]

%% Actuators - Reaction wheels (RW)

simData.rw.rwAllocationMatrix = ... 
    rwAllocationMatrix; % RW allocation matrix

simData.rw.rwInertia = ... 
    rwInertia .* ones(3, 1); % Inertia moment of the RWs around their rotation axis (column vector) [kgm2]

simData.rw.rwMaxOmg = ... 
    (rwMaxOmg * (pi / 30)) .* ones(3, 1); % Maximum angular velocity of the RW (column vector) [rads-1]

%% Actuators - Magnetorquers (MTQ)

simData.mtq.mtqAllocationMatrix = ... 
    mtqAllocationMatrix; % MTQ allocation matrix

simData.mtq.mtqResistance = ... 
    mtqResistance .* ones(3, 1); % Electrical resistance of the MTQs [Ohm]

simData.mtq.mtqMagneticGain = ... 
    mtqMagneticGain .* ones(3, 1); % Magnetic gain of the MTQs [Am2A-1]

simData.mtq.mtqMaxVoltage = ... 
    mtqMaxVoltage .* ones(3, 1); % Maximum voltage to the MTQ [V]

%% Actuators - Reaction Control System (RCS)

simData.rcs.rcsNumThrusters = ... 
    rcsNumThrusters; % Number of thrusters [#]

simData.rcs.rcsPositionMatrix = ... 
    rcsPositionMatrix'; % RCS thrusters position matrix (Body frame, stacked by columns) [m]

simData.rcs.rcsDirectionMatrix = ... 
    rcsDirectionMatrix'; % RCS thrusters direction matrix (Body frame, stacked by columns) [-]

simData.rcs.rcsIsp = ... 
    rcsIsp * ... 
    simData.cts.g0CelBod .* ... 
    ones(simData.rcs.rcsNumThrusters, 1); % RCS specific impulse [ms-1]

simData.rcs.rcsMaxMdot = ... 
    rcsMaxMdot .* ... 
    ones(simData.rcs.rcsNumThrusters, 1); % RCS maximum mass flow rate [kgs-1]

%% Actuators - Initial states
% MTQ and RCS assumed to be initialized at 0 output

simData.ic.rwInitOmg = ... 
    rwInitOmg * (pi / 30); % Initial angular velocities of the RW [rads-1]

%% Assemble initial state bus
% (Must match the field names, dimensions and data types in "state_bus"

simData.ic.initBus = struct( ... 
    'posEci', simData.ic.r0, ... 
    'velEci', simData.ic.v0, ... 
    'qEci2Bod', simData.ic.att0, ... 
    'omegaBod2Eci', simData.ic.omg0, ... 
    'posEcef', simData.ic.r0Ecef, ... 
    'velEcef', simData.ic.v0Ecef, ... 
    'posLLA', simData.ic.lla0, ... 
    'eci2ecefDCM', simData.ic.initEci2EcefDCM, ... 
    'totMass', simData.ic.initFuelMass + simData.massProperties.dryMass, ... 
    'fuelMass', simData.ic.initFuelMass, ... 
    'inertia', simData.massProperties.fullInertia, ... 
    'timeStampPosix', simData.ic.initTimeUTCPosix, ... 
    'timeStampJulian', simData.ic.initTimeJulian);

end