%
% This function preprocesses the input data declared in the supplied input
% file
%
% Input(s):
%   - inpFileName: String, name of the selected input function
%
% Output(s):
%   - simData: Struct, simulation data
%

function [simData] = sim_prepro(inpFileName)

simData = struct(); % Initialize output

eval(inpFileName); % Load input data into this function's workspace

%% Simulator parameters
% Fixed-step Runge-Kutta 4 solver is used by default

simData.sim.simTimeStep = ... 
    simTimeStep; % Simulator time-step [s]

simData.sim.simSimulationMode = ... 
    simSimulationMode; % Simulation mode

simData.sim.simFreq = ... 
    1 / simData.sim.simTimeStep; % Main sampling [Hz]

%% Constants

simData.cts = struct(); % Preallocate

if strcmpi(celBod, 'Earth')

    simData.cts.rCelBod = rCelBod; % Celestial body radius [m]
    simData.cts.muCelBod = muCelBod; % Celestial body gravitational parameter [m3s-2]
    simData.cts.ellipsoidModelCelBod = ellipsoidModelCelBod; % Celestial body ellipsoid model
    simData.cts.omgCelBod = omgCelBod; % Celestial body angular velocity [rads-1]
    simData.cts.g0CelBod = g0CelBod; % Celestial body surface gravitational acceleration [ms-2]

    if strcmpi(timeRef, 'J2000')

        % Reference time
        % Instant at which there was no rotation between the ECI and ECEF
        % reference frames

        simData.cts.refTime = ... 
            posixtime(datetime( ... 
            2000, ... 
            1, ... 
            1, ... 
            11, ... 
            58, ... 
            55, ... 
            816, ... 
            'TimeZone', 'UTC'));

    else

        error('The requested time reference: %s is not available', ... 
            timeRef);
        
    end

else

    error('The requested celestial body data: %s is not available', ... 
        celBod);

end

%% Random error seeds
% Initialize seeds of random sources for results repeatability

% Main seed parameters (store for postprocessing purposes)

simData.randSeeds.mainSeed = mainSeed; % Main seed for the simulation
simData.randSeeds.seedsMax = seedsMax; % Max values for random seeds

% Initialize random number generation with the master seed for solution
% repeatibility

rng(simData.randSeeds.mainSeed);

%% Initial conditions

simData.ic = struct(); % Preallocate initial conditions

% Time

simData.ic.initTimeUTC = ... 
    datetime( ... 
    initYear, ... 
    initMonth, ... 
    initDay, ... 
    initHour, ... 
    initMin, ... 
    initSec, ...  
    'TimeZone', 'UTC'); % Initial timestamp (UTC), Matlab datetime format

simData.ic.initTimeUTCPosix = ... 
    posixtime( ... 
    simData.ic.initTimeUTC); % Initial timestamp (UTC), Posix time format

simData.ic.initTimeJulian = ... 
    juliandate(datetime( ... 
    simData.ic.initTimeUTC)); % Initial time (UTC), Julian date format

% Translational state - ECI2ECEF DCM

initCelBodRot = ... 
    (simData.ic.initTimeUTCPosix - ... 
    simData.cts.refTime) * ... 
    simData.cts.omgCelBod; % Initial rotation around Z of the ECEF frame w.r.t ECI [rad]

initCelBodRot = rem(initCelBodRot, 2 * pi); % Wrap to [0, 2pi]

simData.ic.initEci2EcefDCM = [ ... 
    cos(initCelBodRot),      sin(initCelBodRot), 0; ... 
    -1 * sin(initCelBodRot), cos(initCelBodRot), 0; ... 
    0,                       0,                  1]; % Initial ECI 2 ECEF rotation DCM

% Translational state - Inertial

if strcmpi(initCondsTypeTranslational, 'OrbitalParametersCircular')

    if initInc == 0

        [simData.ic.r0, ... % Initial inertial position [m]
            simData.ic.v0 ... % Initial inertial velocity [ms-1]
            ] = keplerian2ijk( ... 
            (initAlt * 1e3) + simData.cts.rCelBod, ... 
            0, ... 
            initInc, ... 
            initRAAN, ... 
            initArgPer, ... 
            initTrueAnomaly, ... 
            trueLon = 0); % Initial position and velocity in inertial frame

    else

        [simData.ic.r0, ... % Initial inertial position [m]
            simData.ic.v0 ... % Initial inertial velocity [ms-1]
            ] = keplerian2ijk( ... 
            (initAlt * 1e3) + simData.cts.rCelBod, ... 
            0, ... 
            initInc, ... 
            initRAAN, ... 
            initArgPer, ... 
            initTrueAnomaly, ... 
            arglat = 0); % Initial position and velocity in inertial frame

    end

    % Translational state - Celestial body centered

    simData.ic.r0Ecef = ... 
        simData.ic.initEci2EcefDCM * ... 
        simData.ic.r0;

    simData.ic.v0Ecef = ... 
        (simData.ic.initEci2EcefDCM * ... 
        simData.ic.v0) - ... 
        cross( ... 
        [0; 0; simData.cts.omgCelBod], ... 
        simData.ic.r0Ecef);
    
    % Translational state - Spherical coordinates
    
    simData.ic.lla0 = ... 
        ecef2lla( ... 
        simData.ic.r0Ecef', ... 
        simData.cts.ellipsoidModelCelBod); % Initial latitude, longitude and altitude [º, º, m]
    
    simData.ic.lla0 = ... 
        [simData.ic.lla0(1) * (pi / 180); ... 
        simData.ic.lla0(2) * (pi / 180); ... 
        simData.ic.lla0(3)]; % Convert lat and lon to radians and stack in column vector

else

    error('The requested translational initial conditions type: %s is not available', ... 
        initCondsTypeTranslational);

end

% Rotational state - Attitude

if strcmpi(initCondsTypeRotational, 'EulerAngles')

    simData.ic.att0 = ... 
        eul2quat( ... 
        [initYaw * (pi / 180), ... 
        initPitch * (pi / 180), ... 
        initRoll * (pi / 180)], ... 
        "ZYX"); % Initial inertial to body quaternion [-]

    simData.ic.att0 = ... 
        convertQuatConv(simData.ic.att0', 4);
    
else

    error('The requested rotational initial conditions type: %s is not available', ... 
        initCondsTypeRotational);

end

% Rotational state - Angular velocity

simData.ic.omg0 = [ ... 
    initOmgX * (pi / 180); ... 
    initOmgY * (pi / 180); ... 
    initOmgZ * (pi / 180)]; % Initial angular velocity in body w.r.t inertial [rads-1]

% Fuel mass

simData.ic.initFuelMass = initFuelMass; % Initial fuel mass [kg]

%% Mass properties

simData.massProperties = struct(); % Preallocate

% Store values

simData.massProperties.dryMass = ... 
    dryMass; % Dry mass of the vehicle [kg]

simData.massProperties.fullMass = ... 
    simData.massProperties.dryMass + initFuelMass; % Full vehicle mass [kg]

simData.massProperties.dryInertia = ... 
    dryInertia; % Inertia tensor of the vehicle without fuel [kgm2]

simData.massProperties.fullInertia = ... 
    fullInertia; % Inertia tensor of the vehicle with fuel [kgm2]

% Prepare inertia tensor interpolation

simData.massProperties.inertiaBP = ... 
    [0, simData.massProperties.fullMass]; % Breakpoints for the matrix interpolation

simData.massProperties.inertiaTab = ... 
    zeros( ... 
    size(simData.massProperties.dryInertia, 1), ... 
    size(simData.massProperties.dryInertia, 2), ... 
    length(simData.massProperties.inertiaBP)); % Preallocate

simData.massProperties.inertiaTab(:, :, 1) = ... 
    simData.massProperties.dryInertia; % First matrix page

simData.massProperties.inertiaTab(:, :, 2) = ... 
    simData.massProperties.fullInertia; % Second matrix page

%% Aerodynamic properties

simData.aero.refSurf = ... 
    refSurf; % Reference aerodynamic surface [m2]

simData.aero.dragCoeff = ... 
    dragCoeff; % Drag coefficient (assumed constant) [-]

%% External torque disturbances

simData.pert.extPertMag = ... 
    extPertMag * 1e-3; % Torque of the random external perturbations (3 sigma) [mNm]

simData.pert.pertNoiseSeeds = ... 
    round(abs(rand(3, 1)) .* ... 
    simData.randSeeds.seedsMax); % Seeds for the random perturbations

%% Actuators - Reaction wheels (RW)
% All wheels assumed to have the same specs

simData.rw.rwAllocationMatrix = ... 
    rwAllocationMatrix; % RW allocation matrix

simData.rw.rwInertia = ... 
    ((rwStoredH .* 1e-3) / ... 
    (rwRpm4StoredH * (pi / 30))) .* ... 
    ones(size(simData.rw.rwAllocationMatrix, 2), 1); % Inertia moment of the RWs around their rotation axis (column vector) [kgm2]

simData.rw.rwMaxOmg = ... 
    (rwMaxOmg * (pi / 30)) .* ... 
    ones(size(simData.rw.rwAllocationMatrix, 2), 1); % Maximum angular velocity of the RW (column vector) [rads-1]

simData.rw.rwMaxTorque = ... 
    (rwMaxTorque * 1e-3) .* ... 
    ones(size(simData.rw.rwAllocationMatrix, 2), 1); % Maximum torque of the reaction wheels [Nm]

%% Actuators - Magnetorquers (MTQ)

simData.mtq.mtqAllocationMatrix = ... 
    mtqAllocationMatrix; % MTQ allocation matrix

simData.mtq.mtqResistance = ... 
    mtqResistance .* ones(3, 1); % Electrical resistance of the MTQs [Ohm]

simData.mtq.mtqMagneticGain = ... 
    mtqMagneticGain .* ones(3, 1); % Magnetic gain of the MTQs [Am2A-1]

simData.mtq.mtqMaxVoltage = ... 
    mtqMaxVoltage .* ones(3, 1); % Maximum voltage to the MTQ [V]

%% Actuators - Reaction Control System (RCS)

simData.rcs.rcsNumThrusters = ... 
    rcsNumThrusters; % Number of thrusters [#]

simData.rcs.rcsPositionMatrix = ... 
    rcsPositionMatrix'; % RCS thrusters position matrix (Body frame, stacked by columns) [m]

simData.rcs.rcsDirectionMatrix = ... 
    rcsDirectionMatrix'; % RCS thrusters direction matrix (Body frame, stacked by columns) [-]

simData.rcs.rcsIsp = ... 
    rcsIsp * ... 
    simData.cts.g0CelBod .* ... 
    ones(simData.rcs.rcsNumThrusters, 1); % RCS specific impulse [ms-1]

simData.rcs.rcsMaxMdot = ... 
    rcsMaxMdot .* ... 
    ones(simData.rcs.rcsNumThrusters, 1); % RCS maximum mass flow rate [kgs-1]

%% Actuators - Initial states
% MTQ and RCS assumed to be initialized at 0 output

simData.ic.rwInitOmg = ... 
    rwInitOmg * (pi / 30); % Initial angular velocities of the RW [rads-1]

%% Sensors - Gyroscope (GYR)

if gyrUpdateFreq == -1
    simData.gyr.gyrUpdateFreq = ... 
        simData.sim.simFreq; % Use base frequency for the sensor
else
    simData.gyr.gyrUpdateFreq = ... 
    gyrUpdateFreq; % Reading frequency of the gyroscope [Hz]
end

simData.gyr.gyrMeasLim = ... 
    [(-1 * gyrMeasLim) .* ones(1, 3), ... 
    gyrMeasLim .* ones(1, 3)] .* ... 
    (pi / 180); % Maximum measurable angular velocity [rads-1]

simData.gyr.gyrARWperChannel = ... 
    gyrARWperChannel * (pi / 180) / sqrt(3600); % Angular Random Walk (Allan variance) [rads^-0.5]

simData.gyr.gyrNoiseSeeds = ... 
    round(abs(rand(3, 1)) .* ... 
    simData.randSeeds.seedsMax); % Seeds for the random noise

%% Sensors - Star tracker (STR)

if strUpdateFreq == -1
    simData.str.strUpdateFreq = ... 
        simData.sim.simFreq;% Use base frequency for the sensor
else
    simData.str.strUpdateFreq = ... 
        strUpdateFreq; % Reading frequency of the star tracker [Hz]
end

simData.str.strNoisePerChannel = ... 
    (strNoisePerChannel / 3600) * (pi / 180); % Noise per Euler angle (3 sigma) [rad]

simData.str.strBias = ... 
    (strBiasPerChannel / (3600 * 3)) * ... 
    rand(1, 3) .* (pi / 180); % Noise bias per Euler angle (3 sigma) [rad]

simData.str.strNoiseSeeds = ... 
    round(abs(rand(3, 1)) .* ... 
    simData.randSeeds.seedsMax); % Seeds for the random noise

%% Sensors - Magnetometer (MAG)

if magUpdateFreq == -1
    simData.mag.magUpdateFreq = ... 
        simData.sim.simFreq;% Use base frequency for the sensor
else
    simData.mag.magUpdateFreq = ... 
    magUpdateFreq; % Reading frequency of the magnetometer [Hz]
end

simData.mag.magMeasLim = ... 
    magMeasLim * 1e5; % Maximum measurable magnetic field magnitude per channel [nT]

simData.mag.magNoisePerChannel = ... 
    magNoisePerChannel; % Maximum MAG noise per channel (3 sigma) [nT]

simData.mag.magNoiseSeeds = ... 
    round(abs(randn(3, 1)) .* ... 
    simData.randSeeds.seedsMax); % Seeds for the random noise

%% Sensors - Global Navigation Satellite System (GNSS)

if gnssUpdateFreq == -1
    simData.gnss.gnssUpdateFreq = ... 
        simData.sim.simFreq;% Use base frequency for the sensor
else
    simData.gnss.gnssUpdateFreq = ... 
    gnssUpdateFreq; % Reading frequency of the GNSS receiver [Hz]
end

simData.gnss.gnssHorzAcc = ... 
    gnssHorzAcc; % Horizontal accuracy of the GNSS receiver [m]

simData.gnss.gnssVertAcc = ... 
    gnssVertAcc; % Vertical accuracy of the GNSS receiver [m]

simData.gnss.gnssVelAcc = ... 
    gnssVelAcc; % Velocity accuracy of the GNSS receiver [ms-1]

%% Sensors - RW encoders (RWE)

if rweUpdateFreq == -1
    simData.rwe.rweUpdateFreq = ... 
        simData.sim.simFreq;% Use base frequency for the sensor
else
    simData.rwe.rweUpdateFreq = ... 
    rweUpdateFreq; % Reading frequency of the RWE [Hz]
end

%% GNC - Execute prepro here

%% GNC - Control - Vehicle parameters
% The vehicle parameters are duplicated in the simData structure to enable
% the deviation from nominal values in the dynamics without GNC knowledge

% Mass properties

simData.gnc.massProperties.dryMass = ... 
    dryMass; % Dry mass of the vehicle [kg]

simData.gnc.massProperties.fullMass = ... 
    simData.massProperties.dryMass + initFuelMass; % Full vehicle mass [kg]

simData.gnc.massProperties.dryInertia = ... 
    dryInertia; % Inertia tensor of the vehicle without fuel [kgm2]

simData.gnc.massProperties.fullInertia = ... 
    fullInertia; % Inertia tensor of the vehicle with fuel [kgm2]

% MTQ

simData.gnc.act.mtqAllocationMatrix = ... 
    mtqAllocationMatrix; % MTQ allocation matrix

simData.gnc.act.mtqResistance = ... 
    mtqResistance .* ones(3, 1); % Electrical resistance of the MTQs [Ohm]

simData.gnc.act.mtqMagneticGain = ... 
    mtqMagneticGain .* ones(3, 1); % Magnetic gain of the MTQs [Am2A-1]

simData.gnc.act.mtqMaxVoltage = ... 
    mtqMaxVoltage .* ones(3, 1); % Maximum voltage to the MTQ [V]

simData.gnc.act.mtqMaxMagDip = ... 
    (simData.gnc.act.mtqMaxVoltage ./ ... 
    simData.gnc.act.mtqResistance) .* ... 
    simData.gnc.act.mtqMagneticGain; % Maximum magnitude of the magnetic dipole that can be provided by the MTQ

% RW

simData.gnc.act.rwAllocationMatrix = ... 
    rwAllocationMatrix; % RW allocation matrix

simData.gnc.act.rwInertia = ... 
    simData.rw.rwInertia .* ones(3, 1); % Inertia moment of the RWs around their rotation axis (column vector) [kgm2]

simData.gnc.act.rwMaxTorque = ... 
    (rwMaxTorque * 1e-3) .* ... 
    ones(size(simData.gnc.act.rwAllocationMatrix, 2), 1); % Maximum torque of the reaction wheels [Nm]

simData.gnc.act.rwMaxOmg = ... 
    (rwMaxOmg * (pi / 30)) .* ones(3, 1); % Maximum angular velocity of the RW (column vector) [rads-1]

%% Assemble initial state bus
% (Must match the field names, dimensions and data types in "state_bus"

simData.ic.initBus = struct( ... 
    'posEci', simData.ic.r0, ... 
    'velEci', simData.ic.v0, ... 
    'qEci2Bod', simData.ic.att0, ... 
    'omegaBod2Eci', simData.ic.omg0, ... 
    'posEcef', simData.ic.r0Ecef, ... 
    'velEcef', simData.ic.v0Ecef, ... 
    'posLLA', simData.ic.lla0, ... 
    'eci2ecefDCM', simData.ic.initEci2EcefDCM, ... 
    'totMass', simData.ic.initFuelMass + simData.massProperties.dryMass, ... 
    'fuelMass', simData.ic.initFuelMass, ... 
    'inertia', simData.massProperties.fullInertia, ... 
    'timeStampPosix', simData.ic.initTimeUTCPosix, ... 
    'timeStampJulian', simData.ic.initTimeJulian);

end