% Bus definition function template

function busCell = sensors_bus_def()

% Define bus properties

% User defined

name = strsplit(mfilename, '_'); % Auto name from file name
description = 'Sensors bus';

% Default values

headerFile = ''; % Blank by default
dataScope = 'Auto'; % Auto by default
alignment = '-1'; % -1 by default
preserveElemDim = '0'; % 0 by default

% Define bus elements

elementsCellArray = { ... 
    {'omgBodGYR', [3 1], 'double', 'real', 'Sample'}; ... 
    {'magFieldBodMAG', [3 1], 'double', 'real', 'Sample'}; ... 
    {'qEci2BodSTR', [4 1], 'double', 'real', 'Sample'}; ...  
    {'llaGNSS', [3 1], 'double', 'real', 'Sample'}; ... 
    {'velNedGNSS', [3 1], 'double', 'real', 'Sample'}; ... 
    {'vMagGNSS', [1 1], 'double', 'real', 'Sample'}; ... 
    {'hdgGNSS', [1 1], 'double', 'real', 'Sample'}; ... 
    {'rwOmgRWE', [3 1], 'double', 'real', 'Sample'}; ... 
    {'timeUTCPosix', [1 1], 'double', 'real', 'Sample'}; ... 
    };

% Build bus cell

busCell = {{ ... 
    strcat(name{1}, '_', name{2}), ... 
    headerFile, ... 
    description, ... 
    dataScope, ... 
    alignment, ... 
    preserveElemDim, ... 
    elementsCellArray}};

end