% Bus definition function template

function busCell = state_bus_def()

% Define bus properties

% User defined

name = strsplit(mfilename, '_'); % Auto name from file name
description = 'State bus';

% Default values

headerFile = ''; % Blank by default
dataScope = 'Auto'; % Auto by default
alignment = '-1'; % -1 by default
preserveElemDim = '0'; % 0 by default

% Define bus elements

elementsCellArray = { ... 
    {'posEci', [3 1], 'double', 'real', 'Sample'}; ... 
    {'velEci', [3 1], 'double', 'real', 'Sample'}; ... 
    {'qEci2Bod', [4 1], 'double', 'real', 'Sample'}; ... 
    {'omegaBod2Eci', [3 1], 'double', 'real', 'Sample'}; ... 
    {'posEcef', [3 1], 'double', 'real', 'Sample'}; ... 
    {'velEcef', [3 1], 'double', 'real', 'Sample'}; ... 
    {'posLLA', [3 1], 'double', 'real', 'Sample'}; ... 
    {'totMass', [1 1], 'double', 'real', 'Sample'}; ...
    {'fuelMass', [1 1], 'double', 'real', 'Sample'}; ... 
    {'inertia', [3 3], 'double', 'real', 'Sample'}; ... 
    {'timeStampPosix', [1 1], 'double', 'real', 'Sample'}; ... 
    {'timeStampJulian', [1 1], 'double', 'real', 'Sample'}; ... 
    };

% Build bus cell

busCell = {{ ... 
    strcat(name{1}, '_', name{2}), ... 
    headerFile, ... 
    description, ... 
    dataScope, ... 
    alignment, ... 
    preserveElemDim, ... 
    elementsCellArray}};

end