%
% Postpro of the control function
%

function [] = postpro_control(resName)

%% Identify whether it is a MC run

resContents = dir(strcat('results/', resName));
resContents = resContents(~ismember({resContents.name}, {'.', '..'}));

if length(resContents) == 1
    isMC = false;
else
    isMC = true;
end

%% Select signals for postpro

signals2plot = { ... 
    'simTime', ... 
    'qEci2BodNav', ... 
    'omgBodNav', ... 
    'attEci2Bod', ... 
    'omgBod', ... 
    'gncMode', ... 
    'errorRoll', ... 
    'errorPitch', ... 
    'errorYaw', ... 
    'errorQuat', ... 
    'rollBod', ... 
    'pitchBod', ... 
    'yawBod', ... 
    'rollCmd', ... 
    'pitchCmd', ... 
    'yawCmd', ... 
    'pointingMode'};

%% Initialize figure

fig = figure('Name', 'Control postpro');

tabNames = { ... 
    'Detumbling', ... 
    'Desaturation', ... 
    'Pointing - Target acquisition', ... 
    'Pointing - Fine pointing'};

tabGroup = uitabgroup;
tabs = cell(size(tabNames)); % Preallocate

for ii = 1:numel(tabNames)

    tabs{ii} = uitab( ... 
        tabGroup, ... 
        'Title', tabNames{ii}, ... 
        'BackgroundColor', 'k');

end

tabii = 0;

%% Single shot

if ~isMC

    %% Load variables

    dataFolder = strcat('results/', resName, '/sim1/data/');

    for ii = 1:numel(signals2plot)

        signalFile = strcat( ... 
            dataFolder, ... 
            signals2plot{ii}, ... 
            '.mat'); % Data file

        load( ... 
            signalFile, ... 
            signals2plot{ii}); % Load data

    end
    
    inpDataFile = ... 
        strcat( ... 
        'results/', ... 
        resName, ... 
        '/sim1/simInput/simData.mat');

    load(inpDataFile, 'simData');

    %% Index of the instants in which each control mode is enabled

    idDetumb = find(gncMode == 1); % Detumbling IDs
    idDesat = find(gncMode == 2); % Desaturation IDs
    idPoint = find(gncMode == 3); % Pointing IDs
    
    tPoint = simTime(idPoint); % Time vector when pointing mode is enabled

    idTacq = find(pointingMode == 1); % Target acquisition IDs
    idFP = find(pointingMode == 0); % Fine pointing IDs

    %% Detumbling
    
    % Switch figure

    tabii = tabii + 1;
    axes('Parent', tabs{tabii});
    

    if ~isempty(idDetumb)

        % Plot

    end

    %% Desaturation

    % Switch figure

    tabii = tabii + 1;
    axes('Parent', tabs{tabii});
    

    if ~isempty(idDesat)

        % Plot

    end

    %% Pointing - Target acquisition

    % Switch figure

    tabii = tabii + 1;
    axes('Parent', tabs{tabii});
    

    if ~isempty(idTacq)

        % Plot

        % Euler angles error

        % Plot setup

        spNRows = 3; % Number of subplot rows
        spNCols = 1; % Number of subplot rows
        
        % Plotting data information (Time assumed to be in the X axis)

        dataVar = { ... 
            'rollCmd(idTacq) .* (180 / pi)', 'rollBod(idTacq) .* (180 / pi)'; ... 
            'pitchCmd(idTacq) .* (180 / pi)', 'pitchBod(idTacq) .* (180 / pi)'; ... 
            'yawCmd(idTacq) .* (180 / pi)', 'yawBod(idTacq) .* (180 / pi)'; ... 
            'errorRoll(idTacq) .* (180 / pi)', 'none'; ... 
            'errorPitch(idTacq) .* (180 / pi)', 'none'; ... 
            'errorYaw(idTacq) .* (180 / pi)', 'none'}; % Variables to plot (vars sharing column will be plotted together)

        dataName = { ... 
            'Roll angle'; ... 
            'Pitch angle'; ... 
            'Yaw angle'; ... 
            'Roll angle error'; ... 
            'Pitch angle error'; ... 
            'Yaw angle error'}; % Names of the plotted variables

        dataSymbol = { ... 
            '$\phi $'; ... 
            '$\theta $'; ... 
            '$\psi $'; ... 
            '$\Delta \phi $'; ... 
            '$\Delta \theta $'; ... 
            '$\Delta \psi $'}; % Symbols of the plotted variables

        dataUnits = { ... 
            '$^{\circ }$'; ... 
            '$^{\circ }$'; ... 
            '$^{\circ }$'; ... 
            '$^{\circ }$'; ... 
            '$^{\circ }$'; ... 
            '$^{\circ }$'}; % Units of the plotted variables

        dataColor = { ... 
            'r', 'g'; ... 
            'r', 'g'; ... 
            'r', 'g'; ... 
            'b', 0; ... 
            'b', 0; ... 
            'b', 0}; % Color for the plotted variables

        dataLW = { ... 
            3.5, 1.5; ... 
            3.5, 1.5; ... 
            3.5, 1.5; ... 
            2, 0; ... 
            2, 0; ... 
            2, 0}; % Line weigth for the plotted variables

        dataLS = { ... 
            ':', '-'; ... 
            ':', '-'; ... 
            ':', '-'; ... 
            '-', 0; ... 
            '-', 0; ... 
            '-', 0}; % Line style for the plotted variables

        dataLeg = { ... 
            'Commanded', 'Real'; ... 
            'Commanded', 'Real'; ... 
            'Commanded', 'Real'; ... 
            'none', 'none'; ... 
            'none', 'none'; ... 
            'none', 'none';}; % Legends of the plotted variables

        dataSubplotId = { ... 
            1, ... 
            2, ... 
            3, ... 
            4, ... 
            5, ... 
            6}; % Subplot position of each plotted variable

        % Plot setup

        spNRows = 2; % Number of subplot rows
        spNCols = 3; % Number of subplot rows

        for ii = 1:size(dataVar, 1)

            subplot(spNRows, spNCols, dataSubplotId{ii});

            hold on;

            for jj = 1:size(dataVar, 2)
                
                if ~strcmpi(dataVar{ii, jj}, 'none')

                    eval(strcat('dataii = ', dataVar{ii, jj}, ';')); % Load variable

                    plot( ... 
                        tPoint(idTacq), ... 
                        dataii, ... 
                        'Color', dataColor{ii, jj}, ... 
                        'LineWidth', dataLW{ii, jj}, ... 
                        'LineStyle', dataLS{ii, jj}, ... 
                        'DisplayName', dataLeg{ii, jj});

                end

            end

            tStr = sprintf('%s vs time', dataName{ii});
            yStr = sprintf('%s [%s]', dataSymbol{ii}, dataUnits{ii});
            
            xlabel('Time [s]', 'Interpreter', 'latex');
            ylabel(yStr, 'Interpreter', 'latex');
            title(tStr, 'Interpreter', 'latex');

            grid on;
            grid minor;

            hold off;

            if ~strcmpi(dataVar{ii, 2}, 'none')
                legend('Interpreter', 'latex');
            end

        end

    end

    %% Pointing - Fine pointing

    % Switch figure

    tabii = tabii + 1;
    axes('Parent', tabs{tabii});
    

    if ~isempty(idFP)

        % Plot

        % Euler angles error

        % Plot setup

        spNRows = 3; % Number of subplot rows
        spNCols = 1; % Number of subplot rows
        
        % Plotting data information (Time assumed to be in the X axis)

        dataVar = { ... 
            'rollCmd(idFP) .* (180 / pi)', 'rollBod(idFP) .* (180 / pi)'; ... 
            'pitchCmd(idFP) .* (180 / pi)', 'pitchBod(idFP) .* (180 / pi)'; ... 
            'yawCmd(idFP) .* (180 / pi)', 'yawBod(idFP) .* (180 / pi)'; ... 
            'errorRoll(idFP) .* (180 / pi)', 'none'; ... 
            'errorPitch(idFP) .* (180 / pi)', 'none'; ... 
            'errorYaw(idFP) .* (180 / pi)', 'none'}; % Variables to plot (vars sharing column will be plotted together)

        dataName = { ... 
            'Roll angle'; ... 
            'Pitch angle'; ... 
            'Yaw angle'; ... 
            'Roll angle error'; ... 
            'Pitch angle error'; ... 
            'Yaw angle error'}; % Names of the plotted variables

        dataSymbol = { ... 
            '$\phi $'; ... 
            '$\theta $'; ... 
            '$\psi $'; ... 
            '$\Delta \phi $'; ... 
            '$\Delta \theta $'; ... 
            '$\Delta \psi $'}; % Symbols of the plotted variables

        dataUnits = { ... 
            '$^{\circ }$'; ... 
            '$^{\circ }$'; ... 
            '$^{\circ }$'; ... 
            '$^{\circ }$'; ... 
            '$^{\circ }$'; ... 
            '$^{\circ }$'}; % Units of the plotted variables

        dataColor = { ... 
            'r', 'g'; ... 
            'r', 'g'; ... 
            'r', 'g'; ... 
            'b', 0; ... 
            'b', 0; ... 
            'b', 0}; % Color for the plotted variables

        dataLW = { ... 
            3.5, 1.5; ... 
            3.5, 1.5; ... 
            3.5, 1.5; ... 
            2, 0; ... 
            2, 0; ... 
            2, 0}; % Line weigth for the plotted variables

        dataLS = { ... 
            ':', '-'; ... 
            ':', '-'; ... 
            ':', '-'; ... 
            '-', 0; ... 
            '-', 0; ... 
            '-', 0}; % Line style for the plotted variables

        dataLeg = { ... 
            'Commanded', 'Real'; ... 
            'Commanded', 'Real'; ... 
            'Commanded', 'Real'; ... 
            'none', 'none'; ... 
            'none', 'none'; ... 
            'none', 'none';}; % Legends of the plotted variables

        dataSubplotId = { ... 
            1, ... 
            2, ... 
            3, ... 
            4, ... 
            5, ... 
            6}; % Subplot position of each plotted variable

        % Plot setup

        spNRows = 2; % Number of subplot rows
        spNCols = 3; % Number of subplot rows

        for ii = 1:size(dataVar, 1)

            subplot(spNRows, spNCols, dataSubplotId{ii});

            hold on;

            for jj = 1:size(dataVar, 2)
                
                if ~strcmpi(dataVar{ii, jj}, 'none')

                    eval(strcat('dataii = ', dataVar{ii, jj}, ';')); % Load variable

                    plot( ... 
                        tPoint(idFP), ... 
                        dataii, ... 
                        'Color', dataColor{ii, jj}, ... 
                        'LineWidth', dataLW{ii, jj}, ... 
                        'LineStyle', dataLS{ii, jj}, ... 
                        'DisplayName', dataLeg{ii, jj});

                end

            end

            tStr = sprintf('%s vs time', dataName{ii});
            yStr = sprintf('%s [%s]', dataSymbol{ii}, dataUnits{ii});
            
            xlabel('Time [s]', 'Interpreter', 'latex');
            ylabel(yStr, 'Interpreter', 'latex');
            title(tStr, 'Interpreter', 'latex');

            grid on;
            grid minor;

            hold off;

            if ~strcmpi(dataVar{ii, 2}, 'none')
                legend('Interpreter', 'latex');
            end

        end

    end

end